#!/usr/bin/perl -w

# 这个脚本的主要作用是自动生成系统调用的汇编代码，避免手工编写重复的汇编代码。

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";


sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n"; # 立即数加载指令，将系统调用号加载到 a7
    print " ecall\n";              # 环境调用指令，触发从用户模式到监督者模式的切换
    print " ret\n";                # 返回指令
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("trace");
entry("sysinfo");
